# Pioz Ruby styling for Rails
inherit_gem: { rubocop_rails_pioz: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - test/dummy/**/*

Layout/LineLength:
  Max: 300

Metrics/ClassLength:
  Max: 200
